spring.application.name: order-processing-platform

jwt:
    secret: "your-256-bit-secret-key-base64-encoded="
    access-expiration: 86400000 # 24 ????
    refresh-expiration: 2592000000 # 30 ????
    issuer: "E-Commerce-Auth-Service" # ?????????? ??? ???????